# Generated by Django 4.0.1 on 2025-11-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('aspect_ratio', models.CharField(choices=[('9/16', '9:16'), ('1/1', '1:1'), ('4/5', '4:5'), ('16/9', '16:9'), ('21/9', '21:9'), ('3/2', '3:2'), ('4/3', '4:3'), ('2/3', '2:3')], default='9/16', max_length=255)),
                ('description_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_url', models.URLField(blank=True, null=True)),
                ('blog_json', models.JSONField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('resolution', models.CharField(choices=[('1K', '1K'), ('2K', '2K'), ('4K', '4K')], default='2K', max_length=255)),
                ('aspect_ratio', models.CharField(choices=[('9/16', '9:16'), ('1/1', '1:1'), ('4/5', '4:5'), ('16/9', '16:9'), ('21/9', '21:9'), ('3/2', '3:2'), ('4/3', '4:3'), ('2/3', '2:3')], default='9/16', max_length=255)),
                ('credits_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infographs.template')),
            ],
        ),
    ]
