# Generated by Django 4.0.1 on 2025-11-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographs', '0003_alter_infograph_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infograph',
            name='type',
            field=models.CharField(choices=[('infograph', 'Infograph'), ('flowchart', 'Flowchart'), ('mindmap', 'Mindmap'), ('timeline', 'Timeline'), ('organization_chart', 'Organization Chart')], default='infograph', max_length=255),
        ),
    ]
