# Generated by Django 4.0.1 on 2025-11-25 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_creditpurchase'),
        ('infographs', '0004_infograph_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='aspect_ratio',
        ),
        migrations.AddField(
            model_name='template',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
