# Generated by Django 4.0.1 on 2025-11-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographs', '0005_remove_template_aspect_ratio_template_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
