# Generated by Django 4.0.1 on 2025-11-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographs', '0006_template_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='aspect_ratio',
            field=models.CharField(choices=[('9:16', '9:16'), ('1:1', '1:1'), ('4:5', '4:5'), ('16:9', '16:9'), ('21:9', '21:9'), ('3:2', '3:2'), ('4:3', '4:3'), ('2:3', '2:3')], default='9:16', max_length=255),
        ),
    ]
