# Generated by Django 4.2.13 on 2024-08-04 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0007_account_profile_picture_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infographs",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "InfoGraph",
                "verbose_name_plural": "JSON Files",
            },
        ),
    ]
