# Generated by Django 4.0.1 on 2024-08-20 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infograph',
            options={'verbose_name': 'InfoGraph', 'verbose_name_plural': 'InfoGraph'},
        ),
    ]
