# Generated by Django 4.0.1 on 2025-01-30 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_alter_infograph_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='infograph',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infograph',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='infograph',
            name='width',
            field=models.IntegerField(default=1024),
        ),
    ]
