# Generated by Django 4.0.1 on 2025-01-30 16:13

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0003_infograph_height_infograph_uuid_infograph_width'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infograph',
            options={'ordering': ['-created_at'], 'verbose_name': 'InfoGraph', 'verbose_name_plural': 'InfoGraphs'},
        ),
        migrations.AlterField(
            model_name='infograph',
            name='content',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='infograph',
            name='height',
            field=models.IntegerField(default=1024),
        ),
    ]
