# Generated by Django 4.0.1 on 2025-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_alter_infograph_options_alter_infograph_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infograph',
            name='background_color',
            field=models.TextField(default='#FFFFFF'),
        ),
    ]
