# Generated by Django 4.0.1 on 2025-02-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0005_infograph_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infograph',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
