# Generated by Django 4.0.1 on 2025-02-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0006_alter_infograph_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='infograph',
            name='url_preview',
            field=models.URLField(default='https://ainfographic.com/generated_images/preview.png'),
        ),
    ]
