# Generated by Django 4.0.1 on 2025-02-08 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0007_infograph_url_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infograph',
            name='url_preview',
        ),
        migrations.AddField(
            model_name='infograph',
            name='preview_image_url',
            field=models.URLField(blank=True, default='https://ainfographic.com/static/default-preview.png', help_text='HTTPS URL for the preview image', max_length=500, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
    ]
