# Generated by Django 4.0.1 on 2025-02-08 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0008_remove_infograph_url_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infograph',
            name='preview_image_url',
            field=models.URLField(blank=True, default='https://ainfographic.com/generated_images/preview.png', help_text='HTTPS URL for the preview image', max_length=500, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
    ]
