# Generated by Django 4.0.1 on 2025-02-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0009_alter_infograph_preview_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='infograph',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
