# Generated by Django 4.0.1 on 2025-03-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0011_mediaupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='infograph',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
