# Generated by Django 4.0.1 on 2025-03-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0012_infograph_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='infograph',
            name='template_type',
            field=models.CharField(choices=[('letter', 'Letter'), ('normal', 'Normal')], default='normal', max_length=255),
        ),
    ]
