# Generated by Django 4.2.13 on 2024-07-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_subscriptiontier_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='trial_period_days',
            field=models.IntegerField(default=0),
        ),
    ]
