# Generated by Django 4.2.13 on 2024-07-12 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_subscriptiontier_currency_subscriptiontier_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='billing_cycle_anchor',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 12, 0, 0), null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 12, 0, 0), null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 12, 0, 0), null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 12, 0, 0), null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
