# Generated by Django 4.2.13 on 2024-08-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_usersubscription_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="profile_picture_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
