# Generated by Django 4.0.1 on 2024-08-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_creditpack_account_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpack',
            name='stripe_product_id',
            field=models.CharField(default='arse', max_length=100),
        ),
    ]
