# Generated by Django 4.0.1 on 2024-08-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_magiclink'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifcreation',
            name='gif_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_balance',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
