# Generated by Django 4.0.1 on 2025-02-09 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_account_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpurchase',
            name='account',
        ),
        migrations.RemoveField(
            model_name='creditpurchase',
            name='credit_pack',
        ),
        migrations.RemoveField(
            model_name='gifcreation',
            name='account',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='ai_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='monthly_download_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='is_lifetime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.subscriptiontier'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CreditPack',
        ),
        migrations.DeleteModel(
            name='CreditPurchase',
        ),
        migrations.DeleteModel(
            name='GifCreation',
        ),
    ]
