# Generated by Django 4.0.1 on 2025-02-09 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_creditpurchase_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_download_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='monthly_downloads',
            field=models.IntegerField(default=0),
        ),
    ]
