# Generated by Django 4.0.1 on 2025-02-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_account_last_download_reset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
