# Generated by Django 4.0.1 on 2025-02-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_subscriptiontier_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='trial_period_days',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='trial_end',
        ),
    ]
