# Generated by Django 4.0.1 on 2025-03-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_subscriptiontier_trial_period_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='category',
            field=models.CharField(choices=[('general', 'General Feedback'), ('usability', 'Usability'), ('feature', 'Feature Request'), ('bug', 'Bug Report'), ('other', 'Other')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='rating',
            field=models.IntegerField(blank=True, help_text='User rating from 1-5', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='credit_balance',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
