# Generated by Django 4.0.1 on 2025-03-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_suggestion_category_suggestion_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
