# Generated by Django 4.0.1 on 2025-03-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0002_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cdn_url', models.URLField(max_length=500)),
                ('file_format', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
