# Generated by Django 4.0.1 on 2025-03-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0003_flaticon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaticon',
            name='file_format',
        ),
        migrations.AddField(
            model_name='flaticon',
            name='height',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='flaticon',
            name='width',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
