# Generated by Django 4.0.1 on 2025-03-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0004_remove_flaticon_file_format_flaticon_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='svgicon',
            name='is_line_icon',
            field=models.BooleanField(default=False),
        ),
    ]
