# Generated by Django 4.0.1 on 2025-03-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0006_outlineicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svgicon',
            name='is_line_icon',
        ),
    ]
